unstable_features = true
fn_params_layout = "Compressed"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"
fn_single_line = true
struct_field_align_threshold = 20
struct_lit_width = 60
max_width = 125